### ISSUE TITLE
Checklist de lanzamiento

### ISSUE THREAD

**Issue by danielcarranza** [datauy/ElijoEstudiar#84]
- [x] Analytics
- [x] Botones compartir
- [x] Kit de prensa en web DATA
- [x] Subir app a Catálogo Nacional de Datos Abiertos
- [x] Publicar datos en el Catálogo Nacional de Datos Abiertos
- [x] Preparar mensajes de lanzamiento en RR.SS.

**Comment by danielcarranza** [comment]
Finalmente subí kit de prensa y cierro
